### ISSUE TITLE
Randomly select representation for USA character Set

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-line-integers#118]
We would like the sim to load with a randomly selected explorer representation for the USA default character set. 

This also includes adjusting the region and culture icon to show a four square of potential character options.

**Comment by marlitas** [comment]
The functionality for this has been added into the sim with the above commit. Over to @amanda-phet to review.

**Comment by amanda-phet** [comment]
I am concerned that we didn't think through the implications of this feature and how it will generalize to other sims. 
* This sim has one character. Some sims have many characters (CaV, ESP, etc.). In these cases, will we always randomly choose "a set" to use for US, or will we randomly choose individual characters from many sets? 
* We've avoided randomization in the past at times because it could cause confusion in a classroom if every student is seeing something different on their sim, and the teacher has something different too. This might not be problematic, but I just want to be sure it was considered. Since the character never changes unless you refresh the browser, most people won't realize it's random on startup. If we had it change when pressing reset-all, I think the experience of having a random character would be much clearer. 
* It now looks like the US is the only region that has diversity. Should we show an array of faces for every region (and just use the same icon in every sim to represent the region)? In the case of this sim, we don't have 4 to choose from, but other sims easily do. It seems like a simple solution to have one icon we always use for that region, regardless of the sim, and it can be an array of faces. Otherwise we're going to have to solve some variant of this problem for every sim (which 4 to pick from, and if there are fewer than 4, what other faces do we use, etc.). 

<img width="279" alt="image" src="https://github.com/phetsims/number-line-integers/assets/7852916/c75416b9-673c-4315-a6c7-26de5c61be5a">

@kathy-phet and @marlitas, thoughts? Has anyone else weighed in on this discussion who might have thoughts? Right now I'm only aware of this discussion happening between the three of us.

**Comment by amanda-phet** [comment]
>This sim has one character. Some sims have many characters (CaV, ESP, etc.). In these cases, will we always randomly choose "a set" to use for US, or will we randomly choose individual characters from many sets?

If a set already has a diverse set, we don't need to randomly choose from other regions (e.g. CaV, ESP). If a sim has one character (e.g. as NLI, NLD) we can randomly pick a region. 

>We've avoided randomization in the past at times because it could cause confusion in a classroom if every student is seeing something different on their sim, and the teacher has something different too. This might not be problematic, but I just want to be sure it was considered. Since the character never changes unless you refresh the browser, most people won't realize it's random on startup. If we had it change when pressing reset-all, I think the experience of having a random character would be much clearer.

@kathy-phet doesn't think this is problematic. 
AR: this is a new thing and no sim has done this before, so we don't really know. 
KP: We have the DEIB board. We could ask them to review the sim behavior, on reload there is a new random character selected. In context of classroom of 30 students, what do you think? Also ask what they think of the preferences character selection. Can also get feedback from Jo, Briana, translators. 

@arouinfar also brought up that this could do something strange for PhET-iO state.  
KP: it's not a pedagogical impact, so it seems like clients will be ok with this. JH talked to partners and they said it was a positive that sims would load with different characters. 


>It now looks like the US is the only region that has diversity. Should we show an array of faces for every region (and just use the same icon in every sim to represent the region)? In the case of this sim, we don't have 4 to choose from, but other sims easily do. It seems like a simple solution to have one icon we always use for that region, regardless of the sim, and it can be an array of faces. Otherwise we're going to have to solve some variant of this problem for every sim (which 4 to pick from, and if there are fewer than 4, what other faces do we use, etc.).

We are solving this by removing the icon and just using text for each region. 


**Decision:** 
* Create a new default dropdown option called "Multicultural" that randomly selects from any region available (for sims with just one character). `multi` will be the argument. 
* Keep United States.
* Remove icons
* Redesign the dropdown in Preferences: 
Title: Region and Culture
Add a one-sentence description to the preference section: "Select the portrayal of people, places, or objects in the sim. Images are not intended to represent the entire diversity of a region or culture."

**Comment by amanda-phet** [comment]
After @marlitas implements this, let's share a dev version with @kathy-phet to share with the DEIB board.

**Comment by marlitas** [comment]
I believe this is now ready to review in NLI.

**Comment by amanda-phet** [comment]
I think this is working well. I still wonder if we should refer to the selection as 'Random' or something else to communicate what it's doing. Multicultural makes sense to us because we know it's selecting from multiple cultures, but that word means a lot. Any thoughts about renaming it 'Random'? @kathy-phet @arouinfar @RVieyra 

If we decide to keep it as-is then I think this issue can be closed.

**Comment by arouinfar** [comment]
I prefer 'Multiculutral'. I think it would look a bit strange to see 'Region and Culture: Random', especially as the default option.

![image](https://github.com/phetsims/number-line-integers/assets/8419308/d88bc868-9437-45fe-9311-689bc398773f)

**Comment by RVieyra** [comment]
My preference is "Multicultural" as well.

"Random" seems to suggest that you might get a specific regional group assignment (i.e., you might get the "Asian" set).

**Comment by amanda-phet** [comment]
OK, then let's leave this as it. I believe this can be closed now.

**Comment by marlitas** [comment]
Opening it back up to track the richText preferences control commits

**Comment by marlitas** [comment]
Okay that's in and looking good. Closing
