### ISSUE TITLE
Screen icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#22]
Working on screen and scene icons for this sim. 

Any thoughts on these screen icons?
![image](https://user-images.githubusercontent.com/7852916/64042179-8c9bf800-cb1e-11e9-88b1-f091ffd2e590.png)

For the Generic screen, my thought is I'll simplify it a bit so it doesn't have the point hanging below (just the circle at 2) and the absolute value notation can be closer, but this is just a screenshot for the sake of discussion.

**Comment by jbphet** [comment]
Two quick thoughts:
+ I'd suggest using the magenta in the 2nd icon, since it's a bit more eye catching and is a better contrast with the bluish background used on the actual "Generic" screen.
+ Megan is pretty good at creating things quickly.  Do you think she could create an icon that integrated the three concepts, such as PhET Girl walking with a piggy bank under one arm and a thermometer in her other hand (so it looks like she is checking the air temperature)?

**Comment by amanda-phet** [comment]
>Do you think she could create an icon that integrated the three concepts, such as PhET Girl walking with a piggy bank under one arm and a thermometer in her other hand (so it looks like she is checking the air temperature)? 

@megan-phet will work on a quick sketch of this to share with the group as something to consider.

**Comment by amanda-phet** [comment]
Megan made this sketch:
![image](https://user-images.githubusercontent.com/7852916/64197760-15c76d80-ce44-11e9-9ea7-6a924d78b73e.png)

Thoughts? I think it looks super cute!

**Comment by kathy-phet** [comment]
I think its cute, but am somewhat concerned that the level of detail is too high for an icon in the nav bar?

**Comment by amanda-phet** [comment]
The navbar could just be PhET girl hiking, from the first scene. Or just a pig. It can be simpler.

**Comment by ariel-phet** [comment]
I might do something like hiking with a few elevation tick marks or such? I think you want to have a numberline suggested somehow in the icon, and keep it fairly simple.

**Comment by amanda-phet** [comment]
I like the screen icons so I'll close this issue. Please reopen if you want any further changes.
