### ISSUE TITLE
Potentially use SCENERY_PHET/BackgroundNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-line-integers#24]
On the temperature scene of the first screen, there seem to be very similary background rectangles on numbers on the number line. @jbphet mentioned something in `NumberLineNode.js`. Over in https://github.com/phetsims/graphing-quadratics/issues/135 and https://github.com/phetsims/inverse-square-law-common/issues/79 we made a `BackgroundNode` in common code, now used by GQ and ISLC. Assigning to @jbphet to use it if it works for this sim or to close this issue.

**Comment by SaurabhTotey** [comment]
I migrated NumberLineNode to use `BackgroundNode`. It seems like there are plenty more places in the code where this node could be used. For example, if this were used for the absolute value texts, the code would only need to manage the background's visibility instead of both its size and visibility.

**Comment by jbphet** [comment]
I've integrated `BackgroundNode` into a number of places, and it does save code, but I have a suggestion.  When @zepumph and I were discussing this, I mentioned the `NumberDisplay` node.  That node takes a property and updates the readout and the background size whenever that property changes.  How about having `StringDisplay` (which could be a subclass of `BackgroundNode`) that provides a similar convenience?

Secondly, I ran into an issue where I wanted to update the background color as the label color changed, but that isn't possible with the current implementation.  I would suggest making the `Rectangle` a member that be manipulated (such as changing the fill) OR...

...it struck me as odd to have the sub-option `backgroundOptions` when this node is, in fact, the background.  Why not have it be a subclass of Rectangle and let the options go straight through?  Then the `fill` could be set as needed.

**Comment by zepumph** [comment]
>...it struck me as odd to have the sub-option backgroundOptions when this node is, in fact, the background. Why not have it be a subclass of Rectangle and let the options go straight through? Then the fill could be set as needed.

I investigated this, but having the content node be a child of the background is problematic, for example the opacity of the background then applies to the child. I think it will be better to make the background a public member.

**Comment by zepumph** [comment]
>I've integrated BackgroundNode into a number of places, and it does save code, but I have a suggestion. When @zepumph and I were discussing this, I mentioned the NumberDisplay node. That node takes a property and updates the readout and the background size whenever that property changes. How about having StringDisplay (which could be a subclass of BackgroundNode) that provides a similar convenience?

I looked into supporting NumberDisplay using BackgroundNode. I don't think it is a simple conversion. BackgroundNode is setup to change the background's bounds based on the current bounds of the passed in Node, where in NumberDisplay it is a background the remains statically sizes, and instead as the Property value changes, the text updates and realigns within the static background. 

Over to you @jbphet for review of this comment and the previous one.

**Comment by jbphet** [comment]
> [H]aving the content node be a child of the background is problematic...

Makes sense, having it be a public member sounds good.

> I looked into supporting NumberDisplay using BackgroundNode. I don't think it is a simple conversion...

That's not quite what I was suggesting.  I was thinking that it might be good to have a `StringDisplay` node that was similar to `NumberDisplay` in that it takes a string property and the user updates the value of that property in order to update the node.  Upon further reflection, I don't think that gains us much, other than a similar API to that of `NumberDisplay`, and that seems of marginal value to me.  Updating the `Text` node's string value using the `.text =` approach seems just as convenient.  So, let's not worry about it, and I'll close this issue.  Thanks for your efforts on this @zepumph - it saved a fair bit of code in the sim.

**Comment by zepumph** [comment]
I think that sounds very excellent. Furthermore I wanted to add another reason that I gave up was that I couldn't of how `StringDisplay` could gain anything from extending `BackgroundNode`.
