### ISSUE TITLE
9/16/19 interview summary

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#25]
I interviewed one 5th grade student (currently in 6th grade math). 

Student begins on the “scenes” screen and drags all of the objects above and below the water level. On the bank scene he drags the pigs right away as well as pressing the buttons (even simultaneously). After playing with temperatures a bit I prompt him to try some of the checkboxes. He plays on the generic screen and immediately changes the scale so he can put all 3 points at very different locations on the number line. He thinks the opposite is “interesting.” When he has the labels turned off, I notice that he is forced to look at the comparison statement to determine the value of the point- this could be desirable or undesirable. I asked some general questions about what the sim is about, what is absolute value, and what is a negative number. He had not previously learned about absolute value and described it as “how far you are from the base number, in this case 0” and I think the sim helped him to understand! 

A few fixes/bugs: 
1. The parachute is still in front of the comparison statement and we discussed moving it behind that accordion box.
2. For some reason both pigs can have the same value, and the student had them both at the same value multiple times. [bug]
3. Most of the labels have that white transparent background, but I noticed the absolute value notation on the Generic screen still does not. I think we should add it there to be as consistent as possible. 
4. I'm going to email David Webb about a few pedagogical questions I have about 0.

**Comment by amanda-phet** [comment]
@jbphet items 1-3 are  for you. Would you like separate issues made?

**Comment by SaurabhTotey** [comment]
2 is also documented in https://github.com/phetsims/number-line-integers/issues/13.

**Comment by jbphet** [comment]
@amanda-phet - I'm turning this over to you to test the latest behavior.  Here are some specific notes:

>The parachute is still in front of the comparison statement[.]

Should be fixed.

> For some reason both pigs can have the same value[.]

I've implemented a way to handle this that seems pretty decent, but there are some tradeoffs versus other ways of handling this (you and I discussed this over Slack).  Please test the latest behavior and, if you're good with it, we'll just close this issue.  If not, please note what you'd like to try in https://github.com/phetsims/number-line-integers/issues/13 so that we track this in a separate and more specific issue.

> Most of the labels have that white transparent background, but I noticed the absolute value notation on the Generic screen still does not.

It's been added, please verify that it looks correct.

> I'm going to email David Webb about a few pedagogical questions I have about 0.

Sounds good.  If there are any changes we need to make, let's create a specific issue for them.
