### ISSUE TITLE
Quick review of screen 2

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-integers#3]
We did a review of screen 2 last week and recorded a number of changes.  These have been implemented, and I thought it would be good to do another round, since I'm moving on to screen 1 so it would be good to make any further changes while this is fresh in my mind.  We're not looking for small, pixel-polishing sort of feedback here - that will come later.  This is more about any major functionality that should be added or changed.

Assigning to @amanda-phet first, she can include others as she sees fit.

Link:  https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-dev.2/phet/number-line-integers_en_phet.html

**Comment by amanda-phet** [comment]
I reviewed it an it all looks good functionality-wise. I would like the absolute value statement to also have that transparent white background (similar to the labels), and mention it now because it feels less minor than the other pixel-polishes I will request. 

@kathy-phet should also look it over since she will remember things from our design discussions that I could easily have forgotten!

**Comment by jbphet** [comment]
@amanda-phet, @kathy-phet, and I met last week and reviewed the latest version, and several changes were requested (see https://github.com/phetsims/number-line-integers/issues/3).  I think this issue can be closed.
