### ISSUE TITLE
Include Go Lab as a collaborator 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-line-integers#36]
When listing team members for this sim we should include "and in cooperation with Go Lab". 

When making the sim visible on the website, add "Go Lab" to the Thanks to section of the credits on the sim page.

**Comment by jbphet** [comment]
There is a "Thanks" section in sim credits, and it seems to me that this would be an appropriate place for any mention of Go Lab.  The screenshot below shows what this looks like for MLL in Ohm's Law.  Agreed?  If so, let's decide on the exact wording.  If not, is there some particular reason that we have them listed as a team member?  

![image](https://user-images.githubusercontent.com/3082831/67518273-aca0f100-f661-11e9-81a8-2b2376bdb6ff.png)

**Comment by amanda-phet** [comment]
I was following what @arouinfar did for a recent science sim that included GoLab as a collaborator. 

For this sim, they gave specific design feedback as well as a financial contribution.

**Comment by jbphet** [comment]
I just searched through the code base and didn't see any references to "Go Lab" , "Go Labs", "GoLab", or "GoLabs", so maybe @arouinfar hasn't had it added yet.  Adding her as an assignee so that she can perhaps fill us in.

**Comment by arouinfar** [comment]
@jbphet here's what I had said in the email chain about the credits.

> In Masses and Springs: Basics and Energy Forms and Changes we added this to the end of the team section: "and in cooperation with the Next-Lab project". We also added "Next-Lab project" to the Thanks to section of the credits on the sim page.
>
>I'm not totally sure of the organizational structure, but our collaborators were technically part of the Next-Lab project which falls under the Go-Lab umbrella.

**Comment by amanda-phet** [comment]
Thanks @arouinfar . 

I can check with @kathy-phet about what we should say.

**Comment by kathy-phet** [comment]
Match what we did in Energy Forms and Changes. Thanks!

**Comment by jbphet** [comment]
There is no mention of Go-Lab in the EFAC credits, but there is a mention of Next-Lab.  I googled on Go-Lab and found https://nextlab.golabz.eu/initiative, and the banner on that site looks like this:

![image](https://user-images.githubusercontent.com/3082831/67895462-292f4600-fb20-11e9-81c0-3e4cc67e3395.png)

So, it seems like Next-Lab and Go-Lab are closely related, though I don't know the details.  I'll add the same line to the credits in this sim, since that's apparently what the customer wanted.

For reference, the EFAC issue where this was discussed is https://github.com/phetsims/energy-forms-and-changes/issues/50.

**Comment by jbphet** [comment]
This has been committed to master and is available there, and looks like this (don't worry about the other field values just yet - I'll update them before publication):

![image](https://user-images.githubusercontent.com/3082831/67896008-2123d600-fb21-11e9-95a6-4d3bc6e37eab.png)

**Comment by jbphet** [comment]
@kathy-phet and @amanda-phet - good to go on this?

**Comment by amanda-phet** [comment]
Looks good, thanks. 

I will keep this assigned to me so I remember to add Next-Lab to the credits when making the sim visible.

**Comment by kathy-phet** [comment]
I was reviewing the open issues and noticed this is slightly different than the MASB one. We don't use the word "and" in that one. I think it is slightly nicer because we seem to never use "and" anywhere in the credits. 
![image](https://user-images.githubusercontent.com/5096804/71853338-50624080-3098-11ea-80d0-bc46b68ec4b7.png)

JB - You can decide if you want to make it consistent with MASB.

**Comment by amanda-phet** [comment]
@jbphet copied what was done in EFAC, and EFAC uses "and." 

@kathy-phet - you decide what you'd prefer moving forward, and we can make an issue in either EFAC or MASB to update to match the preferred syntax.

**Comment by jbphet** [comment]
IMO, the attribution reads a lot better with the "and" in place.  The example shown in https://github.com/phetsims/number-line-integers/issues/36#issuecomment-571341806 uses neither a comma nor an "and", and as a result sounds to me like Kathy Perkins was somehow associated with Next-Lab.

**Comment by kathy-phet** [comment]
OK. I'm fine with leaving it as is. Just had noted the difference.

**Comment by jbphet** [comment]
Thanks for the input, sound like it is good as is.  Closing.
