### ISSUE TITLE
Comparison statement accordion button/title bigger?

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/number-line-integers#47]
Accordion button seems sort of small given this important concept idea. Maybe make that 18 font and bigger button - like in Gas Properties?

**Comment by amanda-phet** [comment]
I don't think the button needs to be any bigger, since minimizing this statement isn't an important concept. I'm fine with making the title font larger. @jbphet please make the titles 18pt.

@kathy-phet we should make it a priority to revisit our default font sizes across common code, or at least the font size we ultimately want should be standardized (since changing common code can be really costly).

**Comment by jbphet** [comment]
Done, looks good to me, closing.
