### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#61]
Memory Test for https://github.com/phetsims/QA/issues/457:
Start: 33.4
1 min: 46.6
2 min: 58.9
3 min: 68.7
4 min: 78.5
5 min: 86.8
6 min: 95
7 min: 105
8 min: 114
9 min: 122
10 min: 129
11 min: 137
12 min: 145
13 min: 153
14 min: 161
15 min: 174

**Comment by jbphet** [comment]
The memory leak was due to two things:
+ the point controller for the comparison point in the bank scene was getting recreated, and the old one was not being disposed
+ a removal listener was not itself being removed from the observable array of pointer for the number line

Fixing the first of these also fixed an issue where there was sometimes a visible delay in the full rendering of the comparison point controller (i.e. the upper piggy bank) in the bank scene.

Here are the results of a 10-minute memory test on a built version in a Chrome incognito window after these changes:

Start: 35.5
1 min: 39.2
2 min: 40.4
3 min: 41.4
4 min: 41.4
5 min: 41.6
6 min: 42.4
7 min: 42.1
8 min: 41.9
9 min: 42.0
10 min: 42.8

This looks reasonable, and as though there is no significant leak.  I'm going to leave this open but unassigned and have it verified at either a dev or an RC test before publication.

**Comment by jbphet** [comment]
I just tested the RequireJS version on master to make sure there aren't any obvious leaks before creating a release branch.  It looks pretty good.  Below is a screenshot of 8 minutes worth of fuzz testing with an initial, non-fuzz baseline for snapshot 1.

![image](https://user-images.githubusercontent.com/3082831/71755767-937aa480-2e49-11ea-9093-fe7f5f4230da.png)

**Comment by KatieWoe** [comment]
Memory test results for https://github.com/phetsims/QA/issues/465
![mumresults](https://user-images.githubusercontent.com/41024075/71935633-85d46000-3164-11ea-9845-74e618a393f2.png)
