### ISSUE TITLE
Thermometer labels can get slightly too long

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#80]
For https://github.com/phetsims/QA/issues/465
When strings are long the max width of the "A, B, C" labels for thermometers is a bit longer than the thermometer itself. The rtl string test is easiest to see, but any string test with more than one character will show it. These strings are unlikely to have long translations, so this is a lower priority issue.
![longthermometer](https://user-images.githubusercontent.com/41024075/72277595-68cde000-35ef-11ea-9222-570fc4d393f4.png)

**Comment by amanda-phet** [comment]
@jbphet I discussed this with Katie and I think a max width makes sense here so the top of the letters don't get cut off.

**Comment by jbphet** [comment]
A max width value was already in place, but I've made it smaller and also a function of the thermometer width so that the size can be changed without having to also tweak the `maxWidth` value.  It seems to be working well in my tests.  

I wouldn't worry about anything more than a two-letter label as the max in further testing, since no translator in their right mind with use a long string here.

**Comment by KatieWoe** [comment]
StringTest double looks ok in rc.2
