### ISSUE TITLE
IE leaves behind color

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-integers#82]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
IE
**Problem description**
For https://github.com/phetsims/QA/issues/466.
Fairly minor graphical issue with IE. When dragging the thermometers around, their labels on the number line can leave behind a colored line. It seems to go away when you lift up the mouse.

**Visuals**
![colorleftbehind](https://user-images.githubusercontent.com/41024075/72837714-32760d80-3c4c-11ea-9db0-71cf907b6d56.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
  
Name: ‪Number Line: Integers‬

URL: https://phet-dev.colorado.edu/html/number-line-integers/1.0.0-rc.2/phet/number-line-integers_en_phet.html

Version: 1.0.0-rc.2 2020-01-21 16:03:10 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; rv:11.0) like Gecko

Language: en-US

Window: 1536x750

Pixel Ratio: 2.5/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
I spent some time on this, and I could make the problem go away by setting `boundsMethod: 'accurate'` on the text in the readout, but this reduced performance drastically and made dragging of the thermometers laggy, so it was clearly not a good solution.  Oddly, after reverting the accurate bounds change, I could no longer get the problem to happen at all, so it was hard to continue working on it.

Since this is on IE only (which is a small proportion of our users), is not very noticeable, and the artifacts go away as soon as the thermometer is released, I'm going to propose that we not worry about this one.  Assigning to @ariel-phet to see if he concurs, if so he can close.

**Comment by jbphet** [comment]
I discussed this with @ariel-phet in person, and he agreed that this isn't worth the time to pursue further.  Closing.
